name: country_city_kit

description: A lightweight Flutter package for countries, states, and cities.

version: 1.1.1

homepage: https://github.com/byteAnik/country_city_kit

repository: https://github.com/byteAnik/country_city_kit

issue_tracker: https://github.com/byteAnik/country_city_kit/issues

screenshots:
  - description: Preview of country and city selection flow.
    path: assets/preview.gif
  - description: Country selection screen.
    path: assets/image_2.png
  - description: State or city selection screen.
    path: assets/image_3.png
  - description: Selected country and city result screen.
    path: assets/image_1.png

topics:
  - country
  - city
  - state
  - flutter
  - location

environment:
  sdk: ">=3.4.1 <4.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.25.6
