/// Provides country names and their related city, state, or region names.
///
/// The data is stored in memory and can be accessed directly through
/// [countryCityMap] or through the convenience methods [getCountries],
/// [getCities], and [hasCountry].
class CountryCityData {
  /// Maps each supported country name to its available city, state, or region
  /// names.
  ///
  /// Country matching is case-sensitive. Use [getCountries] to inspect the
  /// exact country names supported by this package.
    static final Map<String, List<String>> countryCityMap = {
    'America': [
    'Alabama',
    'Alaska',
    'Arizona',
    'Arkansas',
    'California',
    'Colorado',
    'Connecticut',
    'Delaware',
    'Florida',
    'Georgia',
    'Hawaii',
    'Idaho',
    'Illinois',
    'Indiana',
    'Iowa',
    'Kansas',
    'Kentucky',
    'Louisiana',
    'Maine',
    'Maryland',
    'Massachusetts',
    'Michigan',
    'Minnesota',
    'Mississippi',
    'Missouri',
    'Montana',
    'Nebraska',
    'Nevada',
    'New Hampshire',
    'New Jersey',
    'New Mexico',
    'New York',
    'North Carolina',
    'North Dakota',
    'Ohio',
    'Oklahoma',
    'Oregon',
    'Pennsylvania',
    'Rhode Island',
    'South Carolina',
    'South Dakota',
    'Tennessee',
    'Texas',
    'Utah',
    'Vermont',
    'Virginia',
    'Washington',
    'West Virginia',
    'Wisconsin',
    'Wyoming',
  ],
  'Austria': [
  'Burgenland',
  'Carinthia',
  'Lower Austria',
  'Salzburg',
  'Styria',
  'Tyrol',
  'Upper Austria',
  'Vienna',
  'Vorarlberg',
],
'Belgium': [
  'Antwerp',
  'East Flanders',
  'West Flanders',
  'Flemish Brabant',
  'Limburg',
  'Hainaut',
  'Liège',
  'Namur',
  'Luxembourg',
  'Walloon Brabant',
],
'Denmark': [
  'Capital Region of Denmark',
  'Central Denmark Region',
  'North Denmark Region',
  'Region Zealand',
  'Region of Southern Denmark',
],
'Finland': [
  'Åland Islands',
  'Lapland',
  'North Karelia',
  'Northern Ostrobothnia',
  'Kainuu',
  'North Ostrobothnia',
  'Ostrobothnia',
  'Päijät-Häme',
  'Satakunta',
  'Central Finland',
  'Southern Ostrobothnia',
  'Southern Savonia',
  'Tavastia Proper',
  'Uusimaa',
  'Central Ostrobothnia',
  'Kymenlaakso',
  'South Karelia',
  'Southwest Finland',
  'Pirkanmaa',
],
'France': [
  'Auvergne-Rhône-Alpes',
  'Bourgogne-Franche-Comté',
  'Brittany',
  'Centre-Val de Loire',
  'Corsica',
  'Grand Est',
  'Hauts-de-France',
  'Île-de-France',
  'Normandy',
  'Nouvelle-Aquitaine',
  'Occitanie',
  'Pays de la Loire',
  'Provence-Alpes-Côte d\'Azur',
  'Guadeloupe',
  'Martinique',
  'French Guiana',
  'Réunion',
  'Mayotte',
],
'Albania': [
  'Berat',
  'Dibër',
  'Durrës',
  'Elbasan',
  'Fier',
  'Gjirokastër',
  'Korçë',
  'Kukës',
  'Lezhë',
  'Shkodër',
  'Tirana',
  'Vlorë',
],
'Andorra': [
  'Andorra la Vella',
  'Canillo',
  'Encamp',
  'Escaldes‑Engordany',
  'La Massana',
  'Ordino',
  'Sant Julià de Lòria',
],
'Belarus': [
  'Brest',
  'Gomel',
  'Grodno',
  'Mogilev',
  'Minsk Region',
  'Vitebsk',
  'Minsk City',
],
'Bulgaria': [
  'Blagoevgrad',
  'Burgas',
  'Dobrich',
  'Gabrovo',
  'Haskovo',
  'Kardzhali',
  'Kyustendil',
  'Lovech',
  'Montana',
  'Pazardzhik',
  'Pernik',
  'Pleven',
  'Plovdiv',
  'Razgrad',
  'Ruse',
  'Shumen',
  'Silistra',
  'Sliven',
  'Smolyan',
  'Sofia Province',
  'Sofia City',
  'Stara Zagora',
  'Targovishte',
  'Varna',
  'Veliko Tarnovo',
  'Vidin',
  'Vratsa',
  'Yambol',
],
'Croatia': [
  'Zagreb City',
  'Zagreb County',
  'Krapina‑Zagorje',
  'Sisak‑Moslavina',
  'Karlovac',
  'Varaždin',
  'Koprivnica‑Križevci',
  'Bjelovar‑Bilogora',
  'Primorje‑Gorski Kotar',
  'Lika‑Senj',
  'Virovitica‑Podravina',
  'Požega‑Slavonia',
  'Brodsko‑Posavina',
  'Zadar',
  'Osijek‑Baranja',
  'Šibenik‑Knin',
  'Vukovar‑Srijem',
  'Split‑Dalmatia',
  'Istria',
  'Dubrovnik‑Neretva',
],
'Czechia': [
  'Prague',
  'Central Bohemian',
  'South Bohemian',
  'Plzeň',
  'Karlovy Vary',
  'Ústí nad Labem',
  'Liberec',
  'Hradec Králové',
  'Pardubice',
  'Vysočina',
  'South Moravian',
  'Olomouc',
  'Zlín',
  'Moravian‑Silesian',
],
'Estonia': [
  'Harju',
  'Hiiu',
  'Ida‑Virumaa',
  'Jõgeva',
  'Järva',
  'Lääne',
  'Lääne‑Virumaa',
  'Põlva',
  'Pärnu',
  'Rapla',
  'Saare',
  'Tartu',
  'Valga',
  'Viljandi',
  'Võru',
],
'Germany': [
  'Baden‑Württemberg',
  'Bavaria',
  'Berlin',
  'Brandenburg',
  'Bremen',
  'Hamburg',
  'Hesse',
  'Lower Saxony',
  'Mecklenburg‑Western Pomerania',
  'North Rhine‑Westphalia',
  'Rhineland‑Palatinate',
  'Saarland',
  'Saxony',
  'Saxony‑Anhalt',
  'Schleswig‑Holstein',
  'Thuringia',
],
'Hungary': [
  'Baranya',
  'Bács‑Kiskun',
  'Békés',
  'Borsod‑Abaúj‑Zemplén',
  'Csongrád‑Csanád',
  'Fejér',
  'Győr‑Moson‑Sopron',
  'Hajdú‑Bihar',
  'Heves',
  'Jász‑Nagykun‑Szolnok',
  'Komárom‑Esztergom',
  'Nógrád',
  'Pest',
  'Somogy',
  'Szabolcs‑Szatmár‑Bereg',
  'Tolna',
  'Vas',
  'Veszprém',
  'Zala',
  'Budapest',
],
'Ireland': [
  'Carlow',
  'Cavan',
  'Clare',
  'Cork',
  'Donegal',
  'Dublin',
  'Galway',
  'Kerry',
  'Kildare',
  'Kilkenny',
  'Laois',
  'Leitrim',
  'Limerick',
  'Longford',
  'Louth',
  'Mayo',
  'Meath',
  'Monaghan',
  'Offaly',
  'Roscommon',
  'Sligo',
  'Tipperary',
  'Waterford',
  'Westmeath',
  'Wexford',
  'Wicklow',
],
'Latvia': [
  'Riga',
  'Vidzeme',
  'Kurzeme',
  'Latgale',
  'Zemgale',
],
'Liechtenstein': [
  'Balzers',
  'Eschen',
  'Gamprin',
  'Mauren',
  'Planken',
  'Ruggell',
  'Schaan',
  'Schellenberg',
  'Triesen',
  'Triesenberg',
  'Vaduz',
],
'Lithuania': [
  'Alytus County',
  'Kaunas County',
  'Klaipėda County',
  'Marijampolė County',
  'Panevėžys County',
  'Šiauliai County',
  'Tauragė County',
  'Telšiai County',
  'Utena County',
  'Vilnius County',
],
'Luxembourg': [
  'Capellen',
  'Clervaux',
  'Diekirch',
  'Echternach',
  'Esch‑sur‑Alzette',
  'Grevenmacher',
  'Luxembourg',
  'Mersch',
  'Redange',
  'Remich',
  'Vianden',
  'Wiltz',
],
'Malta': [
  'Central Region',
  'Gozo Region',
  'Northern Region',
  'South Eastern Region',
  'Southern Region',
  'Western Region',
],
'Montenegro': [
  'Podgorica',
  'Nikšić',
  'Herceg Novi',
  'Budva',
  'Bar',
  'Bijelo Polje',
],
'Netherlands': [
  'Drenthe',
  'Flevoland',
  'Friesland',
  'Gelderland',
  'Groningen',
  'Limburg',
  'North Brabant',
  'North Holland',
  'Overijssel',
  'South Holland',
  'Utrecht',
  'Zeeland',
],
'North Macedonia': [
  'Eastern',
  'South‑Eastern',
  'Vardar',
  'Pelagonia',
  'Polog',
  'North‑Eastern',
  'South‑Western',
  'Skopje',
],
'Norway': [
  'Agder',
  'Innlandet',
  'Møre og Romsdal',
  'Nordland',
  'Oslo',
  'Rogaland',
  'Troms og Finnmark',
  'Trøndelag',
  'Vestfold og Telemark',
  'Vestland',
  'Viken',
],
'Poland': [
  'Greater Poland',
  'Kuyavian‑Pomeranian',
  'Lesser Poland',
  'Łódź',
  'Lower Silesian',
  'Lublin',
  'Lubusz',
  'Masovian',
  'Opole',
  'Podlaskie',
  'Pomeranian',
  'Silesian',
  'Subcarpathian',
  'Świętokrzyskie',
  'Warmian‑Masurian',
  'West Pomeranian',
],
'Portugal': [
  'Lisbon',
  'North',
  'Center',
  'Algarve',
  'Alentejo',
  'Madeira',
  'Azores',
],
'Romania': [
  'Alba',
  'Arad',
  'Argeș',
  'Bacău',
  'Bihor',
  'Bistrița‑Năsăud',
  'Botoșani',
  'Brașov',
  'Brăila',
  'Bucharest',
  // … plus all other 32 counties
],
'Russia': [
  'Moscow',
  'Saint Petersburg',
  'Moscow Oblast',
  'Krasnodar Krai',
  'Republic of Tatarstan',
  'Sverdlovsk Oblast',
],
'San Marino': [
  'Acquaviva',
  'Borgo Maggiore',
  'Chiesanuova',
  'Domagnano',
  'Faetano',
  'Fiorentino',
  'Montegiardino',
  'San Marino',
  'Serravalle',
],
'Serbia': [
  'Belgrade',
  'Nišava',
  'South Bačka',
  'Šumadija',
  'Zlatibor',
  'Moravica',
],
'Slovakia': [
  'Bratislava',
  'Trnava',
  'Trenčín',
  'Nitra',
  'Žilina',
  'Banská Bystrica',
  'Prešov',
  'Košice',
],
'Spain': [
  'Andalusia',
  'Catalonia',
  'Madrid',
  'Valencian Community',
  'Galicia',
  'Basque Country',
  'Castile and León',
  'Aragon',
  'Canary Islands',
  'Balearic Islands',
  'Extremadura',
  'Murcia',
  'La Rioja',
  'Navarre',
  'Asturias',
  'Cantabria',
  'Castilla‑La Mancha',
],
'Sweden': [
  'Stockholm County',
  'Uppsala County',
  'Södermanland County',
  'Östergötland County',
  'Jönköping County',
  'Kronoberg County',
  'Kalmar County',
  'Gotland County',
  'Blekinge County',
  'Skåne County',
  'Halland County',
  'Västra Götaland County',
  'Värmland County',
  'Örebro County',
  'Västmanland County',
  'Dalarna County',
  'Gävleborg County',
  'Västernorrland County',
  'Jämtland County',
  'Västerbotten County',
  'Norrbotten County',
],
'Switzerland': [
  'Zurich',
  'Bern',
  'Lucerne',
  'Uri',
  'Schwyz',
  'Obwalden',
  'Nidwalden',
  'Glarus',
  'Zug',
  'Fribourg',
  'Solothurn',
  'Basel‑Stadt',
  'Basel‑Landschaft',
  'Schaffhausen',
  'Appenzell Ausserrhoden',
  'Appenzell Innerrhoden',
  'St. Gallen',
  'Grisons',
  'Aargau',
  'Thurgau',
  'Ticino',
  'Vaud',
  'Valais',
  'Neuchâtel',
  'Geneva',
  'Jura',
],
'Ukraine': [
  'Kyiv',
  'Lviv',
  'Kharkiv',
  'Odessa',
  'Dnipropetrovsk',
  'Donetsk',
],
'United Kingdom': [
  'England',
  'London',
  'Scotland',
  'Wales',
  'Northern Ireland',
],
'Canada': [
  'Alberta',
  'British Columbia',
  'Manitoba',
  'New Brunswick',
  'Newfoundland and Labrador',
  'Nova Scotia',
  'Ontario',
  'Prince Edward Island',
  'Quebec',
  'Saskatchewan',
  'Northwest Territories',
  'Nunavut',
  'Yukon',
],
    'Bangladesh': [
  'Barisal',
  'Chattogram',
  'Dhaka',
  'Khulna',
  'Mymensingh',
  'Rajshahi',
  'Rangpur',
  'Sylhet',
],
'India': [
  'Andhra Pradesh',
  'Arunachal Pradesh',
  'Assam',
  'Bihar',
  'Chhattisgarh',
  'Goa',
  'Gujarat',
  'Haryana',
  'Himachal Pradesh',
  'Jharkhand',
  'Karnataka',
  'Kerala',
  'Madhya Pradesh',
  'Maharashtra',
  'Manipur',
  'Meghalaya',
  'Mizoram',
  'Nagaland',
  'Odisha',
  'Punjab',
  'Rajasthan',
  'Sikkim',
  'Tamil Nadu',
  'Telangana',
  'Tripura',
  'Uttar Pradesh',
  'Uttarakhand',
  'West Bengal',
  'Andaman and Nicobar Islands',
  'Chandigarh',
  'Dadra and Nagar Haveli and Daman and Diu',
  'Delhi',
  'Jammu and Kashmir',
  'Ladakh',
  'Lakshadweep',
  'Puducherry',
],

    'Nepal': [
  'Kathmandu',
  'Pokhara',
  'Lalitpur',
  'Bhaktapur',
  'Biratnagar',
  'Birgunj',
  'Butwal',
  'Bharatpur',
  'Janakpur',
  'Dharan',
  'Hetauda',
  'Nepalgunj',
  'Itahari',
  'Dhangadhi',
  'Tulsipur',
  'Ghorahi',
  'Siddharthanagar',
  'Birtamod',
  'Damak',
  'Rajbiraj',
  'Siraha',
  'Lahan',
  'Gaur',
  'Kalaiya',
  'Malangwa',
  'Baglung',
  'Kawasoti',
  'Tansen',
  'Gorkha',
  'Bidur',
  'Dhankuta',
  'Inaruwa',
  'Khandbari',
  'Besisahar',
  'Putalibazar',
  'Sandhikharka',
  'Tikapur',
  'Lamki Chuha',
  'Chandrapur',
  'Barahathawa',
  'Ilam',
  'Phidim',
  'Chainpur',
  'Manthali',
  'Jaleshwar',
  'Gaushala',
  'Dhading Besi',
  'Dhulikhel',
  'Banepa',
],
    'Bhutan': [
  'Thimphu',
  'Phuntsholing',
  'Paro',
  'Punakha',
  'Wangdue Phodrang',
  'Jakar (Bumthang)',
  'Gelephu',
  'Samtse',
  'Sarpang',
  'Trashigang',
  'Mongar',
  'Trongsa',
  'Zhemgang',
  'Haa',
  'Lhuentse',
  'Pemagatshel',
  'Tashigang',
  'Tashi Yangtse',
  'Samdrup Jongkhar',
  'Dagana',
  'Chukha',
  'Dechencholing',
  'Lungtenphu',
  'Motithang',
  'Babesa',
  'Changangkha',
  'Khuruthang',
  'Nganglam',
],
    
};
  /// Returns the city, state, or region names available for [country].
  ///
  /// Returns an empty list when [country] is not present in [countryCityMap].
  static List<String> getCities(String country) {
    return countryCityMap[country] ?? [];
  }

  /// Returns all country names currently available in [countryCityMap].
  static List<String> getCountries() {
    return countryCityMap.keys.toList();
  }

  /// Returns whether [country] exists in [countryCityMap].
  ///
  /// The lookup is case-sensitive and expects the same spelling returned by
  /// [getCountries].
  static bool hasCountry(String country) {
    return countryCityMap.containsKey(country);
  }
}
